### ISSUE TITLE
[FN] Not able to build on Codeblocks / Visual Studio

### ISSUE THREAD

**Issue by zDEFz** [kroyee/SpeedBlocks-server#1]
I get the following errors:

https://hastebin.com/inunewaxur.tex

**Comment by kroyee** [comment]
ah, yes... we need to put the MingwConverter.cpp/h here aswell as with the client.

**Comment by kroyee** [comment]
It's not compiling in Visual Studio either?
If not, what errors are you getting there?

**Comment by zDEFz** [comment]
Codeblocks and Visual Studio

https://hastebin.com/tudoziroku.tex

**Comment by kroyee** [comment]
Ok, fixed now.

**Comment by zDEFz** [comment]
Works @kroyee
