### ISSUE TITLE
Double free or corruption

### ISSUE THREAD

**Issue by chinatsu** [kroyee/SpeedBlocks-server#2]
I assume you may also have encountered this upon running the server for a while. I'm only raising the issue for posterity, because I'm a little too sleepy to look into it myself.

Here's a gist with the outputted backtrace and memory map
https://gist.github.com/chinatsu/9207838523c9fbb817ecf944326be168

**Comment by kroyee** [comment]
No, I have not actually.
Will take a look at my lists to see what could be causing this.

**Comment by kroyee** [comment]
This happened while playing or was the server idle?

**Comment by chinatsu** [comment]
I am pretty sure nobody was on. I've been running the server for a lot longer than what I had when this happened, so it seems like an edge case

**Comment by kroyee** [comment]
Ok, I did have some lines where I allocated dynamic memory when the server calculated score after a round ended that I changed just now...
But other from that all the dynamic memory is in std::list's and by looking at it I can't see anything that would cause problems.

**Comment by kroyee** [comment]
Hopefully this will take care of the issue. Kind of lucky I caught it in action. :)
Also a bit stupid that I didn't think of it before.
Not very experienced with network-game programming.
